# Generated by Django 4.2.26 on 2025-11-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20241114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='achievementcat',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ('-created_at', 'name')},
        ),
    ]
